# Generated by Django 5.0.3 on 2024-04-01 13:18

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SellDiscount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discount_percent",
                    models.IntegerField(
                        blank=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Скидка в процентах",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        default=datetime.datetime.now, verbose_name="Действует с "
                    ),
                ),
                ("end_date", models.DateField(verbose_name="Окончание")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sell_discount",
                        to="products.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Скидка",
                "verbose_name_plural": "Скидки",
                "ordering": ("product", "discount_percent"),
            },
        ),
        migrations.CreateModel(
            name="SellPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.PositiveIntegerField(verbose_name="Цена")),
                (
                    "start_date",
                    models.DateField(
                        default=datetime.datetime.now,
                        verbose_name="Дата начала действия цены",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Дата окончания действия цены",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sell_price",
                        to="products.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Цена номенклатуры",
                "verbose_name_plural": "Цены номенклатуры",
                "ordering": ("product", "start_date"),
            },
        ),
        migrations.AddConstraint(
            model_name="selldiscount",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("start_date__lte", models.F("end_date")),
                    ("discount_percent__lte", 100),
                ),
                name="unique_sell_discount",
            ),
        ),
        migrations.AddConstraint(
            model_name="selldiscount",
            constraint=models.UniqueConstraint(
                fields=("product", "start_date"), name="unique_discount"
            ),
        ),
        migrations.AddConstraint(
            model_name="sellprice",
            constraint=models.UniqueConstraint(
                fields=("product", "start_date"), name="unique_sell_price"
            ),
        ),
    ]
