# Generated by Django 5.0.3 on 2024-04-07 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sellprice", "0002_remove_sellprice_unique_sell_price_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="selldiscount",
            options={
                "ordering": ("product_id", "discount_percent"),
                "verbose_name": "Скидка",
                "verbose_name_plural": "Скидки",
            },
        ),
        migrations.AlterModelOptions(
            name="sellprice",
            options={
                "ordering": ("product_id", "start_date"),
                "verbose_name": "Цена номенклатуры",
                "verbose_name_plural": "Цены номенклатуры",
            },
        ),
    ]
