# Generated by Django 5.0.3 on 2024-04-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
        ("sellprice", "0004_remove_selldiscount_unique_discount_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="sellprice",
            constraint=models.CheckConstraint(
                check=models.Q(("price__gte", 0)), name="price_greater_than_zero"
            ),
        ),
    ]
