# Generated by Django 5.0.3 on 2024-03-31 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "in_stock",
                    models.IntegerField(default=0, verbose_name="Количество на складе"),
                ),
                (
                    "quantity_shipment",
                    models.PositiveIntegerField(
                        verbose_name="Всего поставленно на склад"
                    ),
                ),
                (
                    "quantity_selling",
                    models.PositiveIntegerField(verbose_name="Всего оплаченных продаж"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="warehouse",
                        to="products.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
        ),
    ]
