# Generated by Django 5.0.3 on 2024-03-31 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BuyOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "time_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Время изменения"),
                ),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False, verbose_name="Статус исполнения"
                    ),
                ),
                (
                    "is_paid",
                    models.BooleanField(default=False, verbose_name="Статус оплаты"),
                ),
                (
                    "supplier",
                    models.CharField(
                        max_length=250, unique=True, verbose_name="Поставщик"
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ на поставку",
                "verbose_name_plural": "Заказы на поставку",
                "ordering": ("supplier", "time_created"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BuyOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=7, verbose_name="Цена за штуку"
                    ),
                ),
                (
                    "discount_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        verbose_name="Цена с учетом скидки",
                    ),
                ),
                ("quantity", models.IntegerField(default=1, verbose_name="Количество")),
            ],
            options={
                "verbose_name": "Составляющие заказа",
                "verbose_name_plural": "Составляющие заказа",
                "ordering": ("product",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SellOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "time_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Время изменения"),
                ),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False, verbose_name="Статус исполнения"
                    ),
                ),
                (
                    "is_paid",
                    models.BooleanField(default=False, verbose_name="Статус оплаты"),
                ),
            ],
            options={
                "verbose_name": "Заказ на продажу",
                "verbose_name_plural": "Заказы на продажу",
                "ordering": ("user",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SellOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=7, verbose_name="Цена за штуку"
                    ),
                ),
                (
                    "discount_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        verbose_name="Цена с учетом скидки",
                    ),
                ),
                ("quantity", models.IntegerField(default=1, verbose_name="Количество")),
            ],
            options={
                "verbose_name": "Составляющие заказа",
                "verbose_name_plural": "Составляющие заказа",
                "ordering": ("product",),
                "abstract": False,
            },
        ),
    ]
