# Generated by Django 5.0.3 on 2024-04-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="sellorderitem",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("quantity__gte", 0), ("discount_price__gte", 0), ("price__gte", 0)
                ),
                name="check_item",
            ),
        ),
    ]
