# Generated by Django 5.0.1 on 2024-01-31 08:44

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорию', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='product',
            name='article_number',
            field=models.IntegerField(blank=True, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='products.category', verbose_name='Категория'),
        ),
    ]
